FROM ubuntu:latest AS picluster_master
RUN apt-get -y update && \
    apt-get -y install ansible openssh-server snapd && \
    apt-get clean && \
    apt-get -y autoremove --purge && \
    ssh-keygen -t rsa -b 4096 -f /root/.ssh/id_rsa -N "P@ssw0rd!" && \
    ssh-keygen -A
CMD ["/bin/mkdir", "/run/sshd"]
["/usr/sbin/sshd", "-D"]