version: "2"

networks:
  gitea:
    external: false

#volumes:
#  gitea:
#    driver: local
#  mysql:
#    driver: local

services:
  server:
    image: gitea/gitea:latest
    environment:
      - SSH_DOMAIN=localhost
      - DISABLE_SSH=true
      - RUN_MODE=prod
      - ROOT_URL="http://localhost:8080/"
      - REQUIRE_SIGNIN_VIEW=true
      - DISABLE_REGISTRATION=true
      - USER_UID=1000
      - USER_GID=1000
      - HTTP_PORT=3000
      - SSH_PORT=22
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
#      - gitea:/data
      - ./gitea:/data
    ports:
      - "8080:3000"
      - "22:22"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
#      - mysql:/var/lib/mysql
      - ./mysql:/var/lib/mysql