#FROM centos:7 AS ansible_master
#RUN yum -y --setopt=tsflags=nodocs update && \
#    yum -y --setopt=tsflags=nodocs install ansible && \
#    yum clean all && \
#    rm -rf /var/cache/yum
FROM alpine:latest AS ansible_master
RUN apk update && \
    apk add --no-cache ansible && \
    rm -rf /tmp/* && \
    rm -rf /var/cache/apk/*