#Inspired by:
# https://medium.com/@tech_phil/running-ansible-inside-docker-550d3bb2bdff

#Usage:
# docker build --tag=ansible_client .
# docker run --rm -d -p 2222:22 --name ansible_client ansible_client
# docker run --rm -d -p 2222:22 --name ansible_client -v D:\Repositories\docker\Ansible\client\id_rsa.pub:/home/ansible/.ssh/authorized_keys ansible_client
# docker ps -a
# docker exec -it ansible_client /bin/bash
# docker stop ansible_client

FROM centos:7 AS ansible_client
RUN yum -y --setopt=tsflags=nodocs update && \
    yum -y install \
        openssh-server \
        sudo && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN groupadd -r ansible && \
    useradd -rmg ansible ansible && \
    sed -i "s/#\ %wheel.*/&\nansible\t\tALL=(ALL)\tNOPASSWD:\ ALL/g" /etc/sudoers
RUN su - ansible -c "mkdir ~/.ssh"

RUN sed -i "s/#StrictModes.*/StrictModes\ no/g" /etc/ssh/sshd_config

RUN ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa

CMD ["/usr/sbin/sshd", "-D"]

EXPOSE 22
#FROM alpine:latest AS ansible_client
#COPY ssh_copy.sh /tmp
#RUN apk update && \
#    apk add --no-cache python openssh-client && \
#    rm -rf /tmp/* && \
#    rm -rf /var/cache/apk/*